### ISSUE TITLE
Support for RestKit

### ISSUE THREAD

**Issue by Ricardo1980** [luisobo/Nocilla#114]
Hello!

I see in your docs:
"Supports NSURLConnection, NSURLSession and ASIHTTPRequest."

Do you support AFNetworking 1/2 and Restkit?

Thanks in advance.

**Comment by luisobo** [comment]
@Ricardo1980 seems that those libraries rely on NSURLConnection and NSURLSession so yeah.

It could definitely be mentioned in the README. Feel free to update it!
