### ISSUE TITLE
Project no longer maintained? 

### ISSUE THREAD

**Issue by ileitch** [luisobo/Nocilla#137]
Hey @luisobo, @robb are you guys still maintaining this project? There hasn't been a release in a while, and there are some commits in master. I am still heavily reliant on this project, and don't want to see it slip behind. I'm happy to take over some maintainer-ship duties if you'd like?

**Comment by andrewkboyd** [comment]
@ileitch I am with you on this as well. This looks like a great solution to what I need, but don't want to install it if it is going to get left behind.  I am happy to help as needed.

**Comment by luisobo** [comment]
Hey guys, I have not been able to put the time. Thanks for volunteering, I granted commit access to you too. I'd be happy to help you guys with any questions you may have. 

Thanks again!

**Comment by ileitch** [comment]
Thanks @luisobo, i'll cut a new release soon.
