### ISSUE TITLE
App store rejection due to private api references

### ISSUE THREAD

**Issue by robseward** [luisobo/Nocilla#142]
After trying to upload a binary to the App Store I received the following email from Apple:

> Non-public API usage:
> 
> The app references non-public selectors in Frameworks/Nocilla.framework/Nocilla: initWithURL:statusCode:headerFields:requestTime:, postBody, requestHeaders

Is there a way to hide these references or disable the compilation of Nocilla when compiling a release build?

**Comment by andydrizen** [comment]
I have created a PR to fix this problem here: https://github.com/luisobo/Nocilla/pull/143

**Comment by andrewkboyd** [comment]
Nocilla should almost certainly not be added to a release build that would go to the App Store. That being said, I see no problem in using public APIs.

I will take a look at the PR

**Comment by andrewkboyd** [comment]
Merged #143.
